name: Sync Upstream and Preserve Configs

on:
  # 手动触发
  workflow_dispatch:
  # 定时检查（每天检查一次）
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-and-preserve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Check for updates and notify
        id: check_updates
        run: |
          python .github/scripts/check_updates.py
        env:
          DIFY_API_KEY: ${{ secrets.DIFY_API_KEY }}
          DIFY_API_ENDPOINT: ${{ secrets.DIFY_API_ENDPOINT }}
      
      - name: Sync with upstream if needed
        if: steps.check_updates.outputs.has_updates == 'true'
        run: |
          # 配置Git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # 添加上游仓库
          git remote add upstream https://github.com/original-author/notionnext.git
          git fetch upstream
          
          # 保存当前配置文件
          python .github/scripts/backup_configs.py
          
          # 合并上游更改
          git merge upstream/main --allow-unrelated-histories
          
          # 恢复个性化配置
          python .github/scripts/restore_configs.py
          
          # 提交更改
          git add .
          git commit -m "Sync with upstream and restore personal configs"
          git push origin main
